name: 'PR Labeler'
description: 'Automatically labels your PRs based on branch name patterns like feature/* or fix/*.'
author: 'Timon van Spronsen'
inputs:
  repo-token:
    description: 'Token for repository'
branding:
  icon: 'tag'
  color: 'white'
runs:
  using: 'node12'
  main: 'index.js'
